from . import sab_classification
from . import project_counter
from . import res_config_settings
from . import project_project
from . import project_customer_portal
from . import sale_order
from . import sab_sale_order_template
from . import sab_offer_lv_order
from . import sab_calculation_item
from . import sab_manufacturer
from . import product_template_extension
from . import product_product_extension
from . import sab_cabinet_product_data
from . import sab_product
from . import sab_product_component
from . import sab_calculation_item_line
from . import sab_supplier
from . import sab_supplier_product
from . import sab_datanorm_surcharge
from . import sab_offer_calculation_group
from . import sab_project_lv_mapping
from . import sab_offer_calculation_line
from . import sab_offer_calculation_runtime
from . import sab_offer_calculation_lv
from . import sab_offer_switchboard
from . import sab_offer_schematic_lv
from . import sab_offer_component_context
from . import sab_offer_calculation_component
from . import sab_offer_reuse_library
from . import sab_offer_release_workflow
from . import sab_offer_release_order_line_security
from . import sab_calculation_change_log
from . import sab_project_bom
from . import sab_employee
from . import sab_employee_confidential
from . import sab_production_order
from . import sab_production_document
from . import sab_production_document_printing
from . import sab_production_employee_runtime
from . import sab_purchase_requirement
from . import sab_switchboard_bom
from . import sab_sale_order_bom_navigation
from . import sab_stock_movement
from . import sab_procurement
from . import project_procurement
from . import sab_procurement_corrections
from . import sab_procurement_roles
from . import sab_procurement_status
from . import sab_procurement_transition_security
from . import sab_procurement_workspace
from . import sab_procurement_workspace_validation
from . import project_procurement_detail
from . import sab_project_document
from . import sab_time_entry
from . import sab_project_controlling
from . import sab_employee_feedback
from . import sab_customer_status
from . import sab_procurement_package
from . import sab_procurement_package_selection_fix
from . import sab_procurement_package_fix
from . import sab_minimum_stock
from . import sab_minimum_stock_fix
from . import sab_delivery_overdue
from . import sab_delivery_overdue_fix
from . import sab_procurement_regression_fixes
from . import sab_procurement_action_domain_fix
from . import sab_odoo_purchase_bridge
from . import sab_odoo_purchase_manual_text_lines
from . import sab_odoo_purchase_bridge_runtime
from . import sab_odoo_purchase_package_fix
from . import sab_odoo_purchase_project_status
from . import sab_odoo_purchase_cancellation_fix
from . import sab_odoo_stock_bridge
from . import sab_odoo_stock_bridge_fix
from . import sab_odoo_stock_field_fix
from . import sab_odoo_commissioning_context_fix
from . import sab_odoo_storable_product
from . import sab_odoo_uom_bridge
from . import sab_odoo_uom_validation
from . import sab_odoo_opening_stock_migration
from . import sab_odoo_commissioning_security_fix
from . import sab_odoo_purchase_approval
from . import sab_odoo_receipt_security_fix
from . import sab_odoo_purchase_approver_edit_security
from . import sab_odoo_purchase_action_security
from . import sab_odoo_uom_19_compat
from . import sab_three_way_match
from . import sab_supplier_confirmation
from . import sab_odoo_stock_destination_fix
from . import sab_legacy_purchase_status_compat
from . import sab_offer_section_parent_fix
from . import sab_odoo_commissioning_picking_type
from . import sab_offer_section_membership_final
from . import sab_odoo_receipt_reservation_fix
from . import sab_procurement_order_quantity_release_fix
from . import sab_odoo_backorder_assignment_fix
from . import sab_odoo_supplier_return_assignment_fix
from . import sab_procurement_standard_order_redirect
